kind: CronJob
apiVersion: batch/v1
metadata:
 name: backup-etcd-cornjob
 namespace: default
spec:
 schedule: "* * * * *"
 jobTemplate:
  spec:
   backoffLimit: 4
   template:
    metadata:
     labels:
      app: etcd1
    spec:
     restartPolicy: Never
     volumes:
      - name: hpvol
        hostPath:
         path: /opt/etcd-backup
     containers:
      - name: etcd
        image: lerndevops/samples:etcdctl
        command: ["sh", "-c", &#39;ETCDCTL_API=3 etcdctl --endpoints=etcdserver:2379 snapshot save "etcd-snapshot-latest-`date +"%d-%m-%Y-%H-%M"`.db"&#39;]
        volumeMounts:
         - name: hpvol
           mountPath: /opt/etcd-backup
