kind: Deployment
apiVersion: apps/v1
metadata:
  name: cm-as-env-data-dep
  namespace: default
spec:
  replicas: 2
  #minReadySeconds:
  #strategy:
  #revisionHistoryLimit: 15
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:  # what is inside pod
      volumes:
        #- name: edvol  # name can be anything
        #  emptyDir: {}
        #- name: hpvol
        #  hostPath:
        #    path: /appconfig  ## this is the path on the worker vm/node where the pod will run
        #- name: cmvol
        #  configMap:
        #    name: filecm
      terminationGracePeriodSeconds: 0 # 0 is forceful delete
      restartPolicy: Always
      containers:
        - name: cont1
          image: nginx:latest
          envFrom:
            - configMapRef:
                name: devdbconfig
          #env:
          #resources:
          #volumeMounts:
          ##    mountPath: /dbconfig
