kind: Deployment
apiVersion: apps/v1
metadata:
 name: grace-period-dep
 namespace: default
spec:
 replicas: 2
 #minReadySeconds:
 #strategy:
 #revisionHistoryLimit: 15
 selector:
  matchLabels:
   app: myapp
 template:
  metadata:
   labels:
    app: myapp
  spec: # what is inside pod
   terminationGracePeriodSeconds: 0 # 0 is forceful delete
   restartPolicy: Always
   containers:
    - name: cont1
      image: lerndevops/samples:pyapp-v1
      env:
      - name: JAVA_HOME
        value: /opt/java
      - name: DBHOST
        value: "10.5.6.7"
      - name: DBPORT
        value: "1543"
      resources:
       requests: # the min amount of resources that are guranteed for the cont on the worker node/vm where it run
        cpu: 20m # 1cpu core on a vm = 1000 milli cpus == 2% of 1cpu core
        memory: 256M
       limits: # the max amount of resource that the cont can take from the worker/vm where it runs
        cpu: 100m
        memory: 1024M
